# Generated by Django 4.1.5 on 2023-02-05 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_class', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='cpf',
            field=models.CharField(blank=True, max_length=11),
        ),
        migrations.AlterField(
            model_name='users',
            name='userType',
            field=models.IntegerField(choices=[(1, 'Admins'), (2, 'Teachers'), (3, 'Students')]),
        ),
    ]
