# Generated by Django 4.1.5 on 2023-02-08 17:08
'migration 2'
from django.db import migrations, models #type:ignore


class Migration(migrations.Migration):
    'migration'
    dependencies = [
        ('e_class', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='userType',
            field=models.IntegerField(choices=[(1, 'Admins'), (2, 'Teachers'), (3, 'Students')]),
        ),
    ]
