# Generated by Django 3.2.17 on 2023-02-09 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('e_class', '0002_alter_users_usertype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('Users_registrationID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='e_class.users')),
            ],
            options={
                'ordering': ['Users_registrationID'],
            },
        ),
    ]
