# Generated by Django 3.2.17 on 2023-02-09 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('e_class', '0005_auto_20230209_0339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='Users_registrationID',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='e_class.users'),
        ),
    ]
