# Generated by Django 3.2.17 on 2023-02-09 18:20

from django.db import migrations, models #type:ignore
import django.db.models.deletion #type:ignore


class Migration(migrations.Migration):

    dependencies = [
        ('e_class', '0007_alter_students_users_registrationid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='Users_registrationID',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='e_class.users'),
        ),
    ]
