# Generated by Django 4.1.6 on 2023-02-09 23:26

from django.db import migrations, models #type:ignore
import django.db.models.deletion #type:ignore


class Migration(migrations.Migration):

    dependencies = [
        ('e_class', '0012_admins'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=45)),
                ('description', models.CharField(max_length=200)),
                ('Admins_Users_registrationID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='e_class.admins')),
            ],
            options={
                'ordering': ['course'],
            },
        ),
    ]
