# Generated by Django 4.1.6 on 2023-02-11 03:09

from django.db import migrations, models # type: ignore
import django.db.models.deletion # type: ignore


class Migration(migrations.Migration):
    dependencies = [
        ("e_class", "0013_subjects"),
    ]

    operations = [
        migrations.CreateModel(
            name="Admin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=45)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("password", models.CharField(max_length=30)),
                ("cpf", models.CharField(max_length=11, unique=True)),
                (
                    "userType",
                    models.IntegerField(
                        choices=[(1, "Admin"), (2, "Teacher"), (3, "Student")]
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=45)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("password", models.CharField(max_length=30)),
                ("cpf", models.CharField(max_length=11, unique=True)),
                (
                    "userType",
                    models.IntegerField(
                        choices=[(1, "Admin"), (2, "Teacher"), (3, "Student")]
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("course", models.CharField(max_length=45, unique=True)),
                ("description", models.TextField(max_length=200)),
                (
                    "admin_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="e_class.admin"
                    ),
                ),
            ],
            options={
                "ordering": ["course"],
            },
        ),
        migrations.CreateModel(
            name="Teacher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=45)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("password", models.CharField(max_length=30)),
                ("cpf", models.CharField(max_length=11, unique=True)),
                (
                    "userType",
                    models.IntegerField(
                        choices=[(1, "Admin"), (2, "Teacher"), (3, "Student")]
                    ),
                ),
                ("specialization", models.CharField(max_length=45)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        # migrations.RemoveField(
        #     model_name="students",
        #     name="Users_registrationID",
        # ),
        # migrations.RemoveField(
        #     model_name="subjects",
        #     name="Admins_Users_registrationID",
        # ),
        # migrations.RemoveField(
        #     model_name="teachers",
        #     name="Users_registrationID",
        # ),
        migrations.DeleteModel(
            name="Admins",
        ),
        migrations.DeleteModel(
            name="Students",
        ),
        migrations.DeleteModel(
            name="Subjects",
        ),
        migrations.DeleteModel(
            name="Teachers",
        ),
        migrations.DeleteModel(
            name="Users",
        ),
    ]
