# Generated by Django 4.1.6 on 2023-02-11 05:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("e_class", "0016_classes_createdat"),
    ]

    operations = [
        migrations.AddField(
            model_name="classes",
            name="teachers",
            field=models.ManyToManyField(to="e_class.teacher"),
        ),
        migrations.AlterField(
            model_name="subject",
            name="admin",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="e_class.admin",
            ),
        ),
    ]
