# Generated by Django 4.1.6 on 2023-02-11 05:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("e_class", "0017_classes_teachers_alter_subject_admin"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subject",
            name="admin",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="e_class.admin",
            ),
        ),
    ]
