# Generated by Django 4.1.6 on 2023-02-11 23:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("e_class", "0018_alter_subject_admin"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="subject",
            options={"ordering": ["name"]},
        ),
        migrations.RenameField(
            model_name="subject",
            old_name="course",
            new_name="name",
        ),
    ]
