# Generated by Django 3.2.17 on 2023-02-12 02:13

from django.db import migrations, models #type: ignore
import django.db.models.deletion #type: ignore


class Migration(migrations.Migration):

    dependencies = [
        ('e_class', '0021_auto_20230211_2311'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscursiveQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('is_visibility', models.BooleanField(default=False)),
                ('statement', models.TextField()),
                ('answer', models.TextField(blank=True, max_length=200)),
                ('students', models.ManyToManyField(to='e_class.Student')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e_class.teacher')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MultipleQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('is_visibility', models.BooleanField(default=False)),
                ('statement', models.TextField()),
                ('option1', models.TextField()),
                ('option2', models.TextField()),
                ('option3', models.TextField(blank=True)),
                ('option4', models.TextField(blank=True)),
                ('answer', models.IntegerField(choices=[(1, 'Option1'), (2, 'Option2'), (3, 'Option3'), (4, 'Option4')])),
                ('students', models.ManyToManyField(to='e_class.Student')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e_class.teacher')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Exams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('startAt', models.DateTimeField()),
                ('endedAt', models.DateTimeField()),
                ('isVisible', models.BooleanField()),
                ('score', models.FloatField()),
                ('discursiveQuestions', models.ManyToManyField(to='e_class.DiscursiveQuestion')),
                ('multipleQuestions', models.ManyToManyField(to='e_class.MultipleQuestion')),
                ('students', models.ManyToManyField(to='e_class.Student')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e_class.teacher')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
