# Generated by Django 4.1.6 on 2023-02-12 08:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("e_class", "0022_discursivequestion_exams_multiplequestion"),
    ]

    operations = [
        migrations.AlterField(
            model_name="classes",
            name="endTime",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="classes",
            name="startTime",
            field=models.DateTimeField(),
        ),
    ]
