# Generated by Django 4.1.6 on 2023-02-12 18:06

from django.db import migrations, models #type: ignore


class Migration(migrations.Migration):
    dependencies = [
        ("e_class", "0025_alter_classes_endtime_alter_classes_starttime"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subject",
            name="teachers",
            field=models.ManyToManyField(related_name="subjects", to="e_class.teacher"),
        ),
    ]
