# Generated by Django 4.1.6 on 2023-02-12 18:12

from django.db import migrations, models #type: ignore
import django.db.models.deletion #type: ignore


class Migration(migrations.Migration):
    dependencies = [
        ("e_class", "0026_alter_subject_teachers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="classes",
            name="students",
            field=models.ManyToManyField(
                related_name="classes",
                through="e_class.Students_has_Classes",
                to="e_class.student",
            ),
        ),
        migrations.AlterField(
            model_name="classes",
            name="subject",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="classes",
                to="e_class.subject",
            ),
        ),
        migrations.AlterField(
            model_name="classes",
            name="teachers",
            field=models.ManyToManyField(related_name="classes", to="e_class.teacher"),
        ),
        migrations.AlterField(
            model_name="exams",
            name="discursiveQuestions",
            field=models.ManyToManyField(
                related_name="exams", to="e_class.discursivequestion"
            ),
        ),
        migrations.AlterField(
            model_name="exams",
            name="multipleQuestions",
            field=models.ManyToManyField(
                related_name="exams", to="e_class.multiplequestion"
            ),
        ),
        migrations.AlterField(
            model_name="subject",
            name="admin",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="subjects",
                to="e_class.admin",
            ),
        ),
    ]
