# Generated by Django 4.1.6 on 2023-02-12 18:16

from django.db import migrations #type: ignore


class Migration(migrations.Migration):
    dependencies = [
        ("e_class", "0027_alter_classes_students_alter_classes_subject_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="discursivequestion",
            name="students",
        ),
        migrations.RemoveField(
            model_name="discursivequestion",
            name="teacher",
        ),
        migrations.RemoveField(
            model_name="multiplequestion",
            name="students",
        ),
        migrations.RemoveField(
            model_name="multiplequestion",
            name="teacher",
        ),
    ]
