# Generated by Django 4.1.6 on 2023-02-12 18:17

from django.db import migrations, models #type: ignore
import django.db.models.deletion #type: ignore


class Migration(migrations.Migration):
    dependencies = [
        ("e_class", "0028_remove_discursivequestion_students_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="discursivequestion",
            name="students",
            field=models.ManyToManyField(
                related_name="discursiveQuestions", to="e_class.student"
            ),
        ),
        migrations.AddField(
            model_name="discursivequestion",
            name="teacher",
            field=models.ForeignKey(
                default=-1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="discursiveQuestions",
                to="e_class.teacher",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="multiplequestion",
            name="students",
            field=models.ManyToManyField(
                related_name="multipleQuestions", to="e_class.student"
            ),
        ),
        migrations.AddField(
            model_name="multiplequestion",
            name="teacher",
            field=models.ForeignKey(
                default=-1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="multipleQuestions",
                to="e_class.teacher",
            ),
            preserve_default=False,
        ),
    ]
