# Generated by Django 4.1.6 on 2023-02-12 19:04

from django.db import migrations, models #type: ignore
import django.db.models.deletion #type: ignore


class Migration(migrations.Migration):
    dependencies = [
        ("e_class", "0029_discursivequestion_students_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="exams",
            name="classe",
            field=models.ForeignKey(
                default=-1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="exams",
                to="e_class.classes",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="exams",
            name="teacher",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="exams",
                to="e_class.teacher",
            ),
        ),
    ]
