# Generated by Django 4.1.6 on 2023-02-12 20:08

from django.db import migrations #type: ignore


class Migration(migrations.Migration):
    dependencies = [
        ("e_class", "0030_exams_classe_alter_exams_teacher"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="classes",
            name="students",
        ),
        migrations.DeleteModel(
            name="Students_has_Classes",
        ),
    ]
