# Generated by Django 4.1.6 on 2023-02-12 20:09

from django.db import migrations, models #type: ignore


class Migration(migrations.Migration):
    dependencies = [
        ("e_class", "0031_remove_classes_students_delete_students_has_classes"),
    ]

    operations = [
        migrations.AddField(
            model_name="classes",
            name="students",
            field=models.ManyToManyField(related_name="classes", to="e_class.student"),
        ),
    ]
