# Generated by Django 4.1.6 on 2023-02-12 20:20

from django.db import migrations, models #type: ignore


class Migration(migrations.Migration):
    dependencies = [
        ("e_class", "0033_alter_multiplequestion_option3_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exams",
            name="endedAt",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="exams",
            name="startAt",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
